/**
Created By : Rajender G
*/


public class AccountHandler {
    list<string> mystring = new List<string>();
    Account[] a2 = new list<account>();
    DateTime t1;
    transient DateTime t2;
    public String getT1() {
        if (t1 == null) t1 = System.now();
        return '' + t1;
            }
    public String getT2() {
        if (t2 == null) t2 = System.now();
        return '' + t2;
            }

            /**RAjender*/
}